using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;

namespace effadatnew
{
    public partial class subjects : DevExpress.XtraEditors.XtraForm
    {
        public subjects()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource2.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource3.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            subjectsTableAdapter1.Fill(effadatDataSet1.Subjects);
            // This line of code is generated by Data Source Configuration Wizard
            subjectsTableAdapter2.Fill(effadatDataSet2.Subjects);
        }
    }
}